name: CI

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-lates
    strategy:
      matrix:
        python-version: [3.8]
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 --count --show-source --statistics src
          flake8 --count --show-source --statistics tests
      - name: Test with unittest
        run: |
          python -m unittest discover
